name: Deploy Application to Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.sandeepc4.sg-host.com
          username: u1471-vgljsoqbpbvx
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfYUIC4isWEqOfLEFE/e7z0vQ8Tx0NMAiAvIYKlkIKpR2hlmS15hQMX/TYC+2fk4FumoKAu1kekyGkP67DMuihXyWyzosKc08bCq57FqpnizSzH8srwbUHauShPahAU21rFJca6JSbacaJDaq/GxtT5h753yTfLPf0NPC1K77n1nuxem5ATDYfikhau0HVqV54F/ml4XajPbeWuIM1SR9tSUnDZJJlFBHJ3hUPAp2KPOHAbQE12luRP7cptcXiS35hgXWIYQdKXlbLzvglwaXRivJq0Od9wDIqqpx9xdyan4BiamVX7oFJS05upo36KNmWO8lqiQvJqFWGqz4j2ceg+ArddZcNh7a5NuNPipgcHKb23YFgaNWSpTQX5DTEEh1Jc243+MjSf8n8CYgYTX4zn8mXJsC5GNnyTgAm20MaNZq2Q7dJxiLNqpkzDGeKbWqFIIgPj9cLYFabPxWsw5nlUTCd/jFS0FxECefxAF9NLH+QSJckjCp1WjLYVvJLhiqGBXsPxU+WQFzdfUWBsLUUGqkIWY6sv4QahW3IdUv2fyiUuHONvuptLI587xQsWyaIwkLNXFJXEvO20641vIHu1Wj78WTU+WCtTlu35vpuyrARISfCKO9A8n1/dfPfEgDFcmHnOiH+aue8Zf/uXdNjka7OqI4GIWrO4pvJ67/mvw==
          port: 18765
          passphrase: bo$g($2_qn4x
          script: |
            cd www
            cd sandeepc4.sg-host.com
            git fetch --all
            git reset --hard origin/main
            git pull
            /usr/local/php82/bin/php-cli artisan optimize:clear
